config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :pokemons do
    resources :bookings, only: [:new, :create]
  end

  resources :pokemons, :pages, :shared

  # Defines the root path route ("/")
  # root "articles#index"
  get "profile", to: "pages#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  has_one_attached :photo
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_one_attached :photo

  # validates :name, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, required: true, autosave: true
  has_one_attached :photo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :pokemons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(strong_params)
    @pokemon = Pokemon.find(params[:pokemon_id])

    @booking.user = current_user
    @booking.pokemon = @pokemon
    if @booking.save
      redirect_to profile_path
    else
      render 'pokemons/show', status: :unprocessable_entity
    end
  end

  private

  def strong_params
    params.require(:booking).permit(:date, :pokemon_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # @pokemon = Pokemon.find(params[:id])
    # @booking = Booking.new
   

    if params[:query].present?
      sql_query = "name ILIKE :query OR element ILIKE :query"
      @pokemons = Pokemon.where(sql_query, query: "%#{params[:query]}%")
    else
      @pokemons = Pokemon.all
    end
  
    # if params[:query].present?
    #   @pokemons = Pokemon.where(name: params[:query])
    # else
    #   @pokemons = Pokemon.all
    # end
    # The `geocoded` scope filters only flats with coordinates
     @markers = @pokemons.geocoded.map do |pokemon|
    {
    lat: pokemon.latitude,
    lng: pokemon.longitude
    }
    end
  end

  # def index
  #   @pokemons = Pokemon.all
  # end

  def show
    @pokemon = Pokemon.find(params[:id])

    @booking = Booking.new

  end
  
  def profile
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = @pokemons.geocoded.map do |pokemon|
      {
        lat: pokemon.latitude,
        lng: pokemon.longitude
      }
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @booking = Booking.new
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def pokemon_params
    params.require(:pokemon).permit(:name, :element, :move, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>PICKAPoke</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="http://fonts.cdnfonts.com/css/pokemon-solid" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.iconify.design/iconify-icon/1.0.0-beta.3/iconify-icon.min.js"></script>
  </head>
  <body>
  <%= render "shared/navbar" %>
  <%# <p class="notice"><%= notice %>
       <%# <p class="alert"><%= alert %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="entire">
  <div class="banner" style="background-image:  linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://assets.pokemon.com//assets/cms2/img/misc/virtual-backgrounds/go/pokemon-party.jpg);">
    <div class="banner-content">
      <h1>Take your pick of our poke</h1>
      <p>Do battle with trainers from around the world</p>
    </div>
  </div>
  <div class="searchbar" style="width: 50vw; padding-left: 43px; padding-right: 43px;">
  <h3>Search for Pokemon</h3>
    <%= form_with url: root_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a Pokemon"
    %>
    <div class="button"><%= submit_tag "Search", class: "btn btn-primary" %></div>
  <% end %>
  </div>
  <div class="main-container">
    <div class="cards">
      <%@pokemons.each do |pokemon| %>
        <%= link_to pokemon_path(pokemon.id), class:"text-decoration-none" do %>
          <div class="card">
            <div class="card-photo"><%= cl_image_tag pokemon.photo.key, width: 100, crop: :fill %>
            </div>
            <h1 class="text-black mt-4"> <%= pokemon.name %></h1>
            <p class="list-group-item text-black"><%= pokemon.element %></p>
            <p class="list-group-item text-black"><%= pokemon.move %></p>
          </div>
        <% end %>
      <% end %>
    </div>
    <div id="map">
      <div class="map" style="height: 100vh; padding-bottom: 40px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="banner" style="background-image:  linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1716861/pexels-photo-1716861.jpeg?cs=srgb&dl=pexels-carolina-castilla-arias-1716861.jpg&fm=jpg);">
  <div class="banner-content">
    <h1>Trainer Profile</h1>
  </div>
</div>

<div class="container py-5">
  <div class="col-7">
    <h1> Account Details: </h1>


    <p id="profile-email"><%=current_user.email%></p>
    <h4> Number of Pokemons: </h4>
    <%= current_user.pokemons.length %>
    <p></p>

    <h4> Names: </h4>
      <% current_user.pokemons.each do |pokemon| %>
      <p> <%= pokemon.name %></p>
      <%= pokemon.image_path %>
      <% end  %>

  <p></p>


  <div class="d-flex align-items-center justify-content-between mb-3">
    <%= link_to "Add your pokemons here", new_pokemon_path, class: "btn btn-primary" %>
  </div>

    <div class="d-flex align-items-center justify-content-between mb-3">
    <h4> <%= link_to "Book a Battle!", class: "btn btn-primary" %> </h4>
   </div>
  </div>
</div>
</div>


  <p></p>

<div class="col-12">
  <div class="container pb-2">
    <h1>My booked pokemons: </h1>
    <p></p>
    <div class="row">
      <% current_user.bookings.each do |booking| %>
        <div class="col-sm-6 col-md-4 col-lg-3">

            <div class="mb-3" style="width: 100%; border-radius: 8px;">
              <div class="card-body">
                <p>Booked for <%= booking.date %></p>
                <p><em>Pokemon: <%= booking.pokemon.name %></em></p>
                <p>Owner: <%= booking.pokemon.user.email %></p>
              </div>
            </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pokemons/new.html.erb
<h1 style="font-family: 'Pokemon Solid', sans-serif;
  letter-spacing: 4px; padding-left: 110px;">Add a new pokemon</h1>
<div class="form" style="width: 50vw; margin-left: 100px">
  <%= simple_form_for(@pokemon) do |f| %>
    <%= f.input :name %>
    <%= f.input :element %>
    <%= f.input :move %>
    <%= f.input :photo, as: :file %>

    <%= f.submit "Add your new pokemon!", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/pokemons/show.html.erb
<div class="banner" style="background-image:  linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1716861/pexels-photo-1716861.jpeg?cs=srgb&dl=pexels-carolina-castilla-arias-1716861.jpg&fm=jpg);">
  <div class="banner-content">
    <h1>Take at look at your chosen Pokemon</h1>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-6" style="padding: 20px;">
      <div class="card-show">
        <div class="card-show-text">
          <%= cl_image_tag @pokemon.photo.key, height: 300, width: 400, crop: :fill %>
          <h1><%= @pokemon.name %></h1>
          <%# <i class="fa-regular fa-fire"></i> %>
          <p><%= @pokemon.element %></p>
          <p><%= @pokemon.move %></p>
        </div>  <%# <iconify-icon id="pokemon-logo" icon="simple-icons:pokemon"></iconify-icon> %>
      </div>
    </div>
    <div class="col-6">
      <div class="row">
        <div class="book-card">
          <h1>Book this Pokemon</h1>
          <div class="form-inputs">
            <%= simple_form_for [@pokemon, @booking] do |f| %>
            <%= f.input :date, html5: true %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Book now", class: "btn btn-primary" %>
            <% end %>
          </div>
          <div>
            <p>This is the owners details</p>
            <p>Mr Pokemons Address</p>
            <p>07649833671</p>
            <i class="fa-solid fa-location-dot"></i>
            <p>SW79 6TY, London, UK</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="profile-card">
          <h1>Pokemon Trainer</h1>
          <img class="avatar dropdown-toggle" src="/assets/avatar-7cb4cd68c9a5e40a849d8d1551a039ac6708f52ed544a3a7aef270730b5fbd7f.png" alt="Profile Image">
          <p>Pokemons: 1</p>
          <p>Rating: 3.98</p>
          <p>Name: Rory</p>
          <p>Surname: Jackson</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer-fluid">
  <p>If you love us as much as you seem to, follow us below...</p>
  <ul style="list-style: none;">
    <li><a href="#" class="fa fa-facebook"></a></li>
    <li><a href="#" class="fa fa-instagram"></a></li>
    <li><a href="#" class="fa fa-twitter"></a></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag src="/assets/Pokemon-6a23310b7aa3734294c21b263d88a651a3172f5b95f5cd698af65817d5aec1d3.png"%>
    <%= link_to root_path, class: "navbar-brand-2" do %>
      <%= image_tag src="https://img.icons8.com/dusk/64/000000/pokemon.png"%>
    <% end %>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item m-3">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-expanded': false %>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to "My Profile", profile_path, class: "dropdown-item" %></li>
              <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
            </ul>
          </li>
          <% else %>
           <li class="nav-item m-3">
              <%= link_to "Login", new_user_session_path, class: "nav-link", data: {turbo: false} %>
           </li>
           <li class="nav-item m-3">
             <%= link_to "Sign-up", new_user_registration_path, class: "nav-link", data: {turbo: false} %>
           </li>
        <% end %>
     </ul>
    </div>
  </div>
</div>